version: '3'

services:
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  dbdata: